import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, rm, stat } from 'node:fs/promises';
import { join } from 'node:path';
import net from 'node:net';
import { Broker } from '../src/broker.mjs';
import { serveBridge } from '../src/bridge-api.mjs';
import { localRequest } from '../src/local-ipc.mjs';
import { manageWeb } from '../scripts/web-service.mjs';

test('stopping/restarting the Web process preserves active turns, receipts, events and approvals', async t => {
  const state = await mkdtemp('/private/tmp/phone-ipc-');
  const listener = net.createServer();
  await new Promise(resolve => listener.listen(0, '127.0.0.1', resolve));
  const port = listener.address().port;
  await new Promise(resolve => listener.close(resolve));
  const config = { state, port, origin: `http://127.0.0.1:${port}`, passwordPath: join(state, 'password'), bridgeSocket: join(state, 'ipc/bridge.sock'), webSocket: join(state, 'ipc/web.sock') };
  const password = 'test-password-not-production';
  await writeFile(config.passwordPath, password, { mode: 0o600 });
  const sent = [];
  const broker = new Broker(message => sent.push(message));
  broker.ready = true;
  const server = await serveBridge(broker, config.bridgeSocket, 'desktop-shared');
  t.after(async () => { await manageWeb('stop', config); server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); await rm(state, { recursive: true, force: true }); });
  assert.equal((await stat(config.bridgeSocket)).mode & 0o777, 0o600);
  await assert.rejects(serveBridge(broker, config.bridgeSocket, 'desktop-shared'), /已运行/);
  await assert.rejects(localRequest(config.bridgeSocket, '/shutdown', {}), /不支持/);
  const first = await manageWeb('start', config);
  assert.equal((await manageWeb('start', config)).pid, first.pid);
  const headers = { Origin: config.origin, 'Content-Type': 'application/json' };
  async function login() {
    const response = await fetch(config.origin + '/api/login', { method: 'POST', headers, body: JSON.stringify({ password }) });
    assert.equal(response.status, 200);
    headers.Cookie = response.headers.get('set-cookie').split(';')[0];
  }
  await login();
  const submission = { key: 'restart-turn-001', method: 'turn/start', params: { threadId: 'owned', input: [{ type: 'text', text: 'test' }] } };
  const request = () => fetch(config.origin + '/api/commands', { method: 'POST', headers, body: JSON.stringify(submission) });
  assert.equal((await request()).status, 202);
  const before = await localRequest(config.bridgeSocket, '/status');
  await manageWeb('stop', config);
  // Simulate real upstream progress while the Web process is absent.
  broker.receive({ id: sent[0].id, result: { turn: { id: 'running-turn' } } });
  broker.receive({ method: 'turn/started', params: { threadId: 'owned', turn: { id: 'running-turn' } } });
  broker.receive({ method: 'item/agentMessage/delta', params: { threadId: 'owned', delta: 'continued offline' } });
  broker.receive({ id: 'approval', method: 'item/commandExecution/requestApproval', params: { threadId: 'owned' } });
  const second = await manageWeb('start', config);
  assert.notEqual(second.pid, first.pid);
  const after = await localRequest(config.bridgeSocket, '/status');
  assert.equal(before.bridgeId, after.bridgeId);
  assert.equal(before.pid, after.pid);
  assert.equal((await fetch(config.origin + '/api/state', { headers })).status, 401);
  await login();
  const snapshot = await (await fetch(config.origin + '/api/state', { headers })).json();
  assert.equal(snapshot.active.owned, 'running-turn');
  assert.ok(snapshot.events.some(e => e.params.delta === 'continued offline'));
  assert.equal(snapshot.approvals[0].id, 'approval');
  const receipt = await (await fetch(config.origin + '/api/commands/restart-turn-001', { headers })).json();
  assert.equal(receipt.status, 'completed');
  assert.equal((await request()).status, 202);
  assert.equal(sent.length, 1, 'Web restart and resubmission must not execute another turn');
  const answer = await fetch(config.origin + '/api/answer', { method: 'POST', headers, body: JSON.stringify({ id: 'approval', result: { decision: 'decline' } }) });
  assert.equal(answer.status, 200);
  assert.equal(sent.length, 2);
  broker.fromDesktop({ id: 'approval', result: { decision: 'accept' } });
  assert.equal(sent.length, 2);
  const third = await manageWeb('restart', config);
  assert.notEqual(third.pid, second.pid);
  assert.equal(broker.snapshot().active.owned, 'running-turn');
});
