// Optional developer dependency: install Playwright separately or provide its module URL.
// Every network request is mocked; no desktop task, password or live server is used.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({channel:'chrome', headless:true});
try {
const page = await browser.newPage({viewport:{width:390,height:844}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
const tasks=[{id:'task-one',name:'周报',cwd:'/Code/alpha',updatedAt:1789370000},{id:'task-two',name:'周报',cwd:'/Code/beta',updatedAt:1789380000}];
const history={turns:[{items:[{type:'userMessage',content:[{type:'text',text:'第一行\n第二行'}]},{type:'agentMessage',text:'# 标题\n说明\n```js\nconst a = 1;\n```\n<img src=x onerror=alert(1)>'},{type:'commandExecution',command:'echo test'}]}]};
history.turns[0].items[1].text += '\n- **重点**\n- `代码`\n\n3. 第三步\n4. 第四步\n\n[文档](https://example.com/docs) [危险](javascript:alert)\n\n| 名称 | 值 |\n| --- | --- |\n| 第一项 | 正常 |';
history.turns[0].items[0].content.push({type:'image',url:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZ1cAAAAASUVORK5CYII='});
const receipts=new Map(); let created, creationParams;
let approvals=[]; const answers=[];
let events=[]; let readKey; const readRequested=Promise.withResolvers();
const active={}; const executions=[];
await page.route('http://localhost:9789/**',async route=>{
 const req=route.request(), url=new URL(req.url()); let data;
 if(url.pathname==='/api/state') data={ready:true,mode:'desktop-shared',bridgeId:'test',cursor:0,events,active,approvals};
 else if(url.pathname==='/api/projects') data={projects:[{id:'/Code/alpha',serverId:'native-alpha',name:'Alpha 项目',roots:['/Code/alpha','/Code/shared']},{id:'/Code/beta',serverId:'native-beta',name:'Beta 项目',roots:['/Code/beta']}],assignments:{'task-one':'/Code/alpha','task-two':'/Code/beta'}};
 else if(url.pathname==='/api/answer') {answers.push(req.postDataJSON());data={ok:true};}
 else if(url.pathname==='/api/commands') {
  const body=req.postDataJSON();
  let result;
  if(body.method==='thread/list') result={data:body.params.searchTerm==='更早任务'?[{id:'older',name:'更早任务',cwd:'/Code/archive'}]:tasks,nextCursor:null};
  else if(body.method==='thread/start') {creationParams=body.params;created=body.params.cwd;result={thread:{id:'new',cwd:created,projectId:body.params.projectId,turns:[]}};}
  else if(body.method==='thread/resume'&&body.params.threadId==='new') {
    receipts.set(body.key,{status:'failed',error:{message:'no rollout found for thread id new'}});
    await route.fulfill({body:JSON.stringify({status:'pending'}),contentType:'application/json'});return;
  }
  else result={thread:{...tasks.find(t=>t.id===body.params.threadId),...history}};
  if(body.method.startsWith('turn/')) {executions.push(body);receipts.set(body.key,{status:'pending'});}
  else if(body.method==='thread/read') {readKey=body.key;receipts.set(body.key,{status:'pending'});readRequested.resolve();}
  else receipts.set(body.key,{status:'completed',result});
  data={status:'pending'};
 } else if(url.pathname.startsWith('/api/commands/')) data=receipts.get(url.pathname.split('/').pop());
 else {const file=url.pathname==='/'?'index.html':url.pathname.slice(1);await route.fulfill({body:await readFile(new URL('../public/'+file,import.meta.url)),contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'});return;}
 await route.fulfill({body:JSON.stringify(data),contentType:'application/json'});
});
await page.goto('http://localhost:9789/');
await page.locator('#choose-task').click();
await page.locator('.task-card').first().waitFor();
assert.equal(await page.locator('.task-card').count(),2);
assert.equal(await page.locator('#project-filter option').nth(1).innerText(),'Alpha 项目');
assert.equal(await page.locator('.project-group[data-project="/Code/beta"] .task-card').count(),1);
await page.locator('#task-search').fill('更早任务');
assert.equal(await page.locator('.task-card').count(),0);
await page.locator('#search-all').click();
await page.waitForFunction(()=>document.querySelector('#task-list').textContent.includes('更早任务'));
assert.equal(await page.locator('.task-card').count(),1);
await page.locator('#recent-tasks').click();
await page.waitForFunction(()=>document.querySelectorAll('.task-card').length===2);
assert.equal(await page.locator('#project-filter option[value="/Code/archive"]').count(),0,'task paths must not invent desktop projects');
await page.locator('#project-filter').selectOption('/Code/beta');
assert.equal(await page.locator('.task-card').count(),1);
await page.locator('#task-search').fill('task-two');
await page.locator('.task-card').click();
await page.waitForFunction(()=>!document.querySelector('#task-dialog').open);
assert.equal(await page.locator('.message').count(),2);
assert.equal(await page.locator('.tool-record').count(),1);
assert.equal(await page.locator('.userMessage .message-body').innerText(),'第一行\n第二行');
assert.equal(await page.locator('.agentMessage h3').innerText(),'标题');
assert.equal(await page.locator('.agentMessage ul li').count(),2);
assert.equal(await page.locator('.agentMessage ol').getAttribute('start'),'3');
assert.equal(await page.locator('.agentMessage a').count(),1);
assert.equal(await page.locator('.agentMessage a').getAttribute('rel'),'noopener noreferrer');
assert.equal(await page.locator('.agentMessage tbody td').last().innerText(),'正常');
assert.ok((await page.locator('.agentMessage pre').innerText()).includes('const a = 1;'));
assert.equal(await page.locator('#history img').count(),1);
await page.waitForFunction(()=>document.querySelector('#history img')?.naturalWidth>0);
assert.equal(await page.locator('#history img[src="x"]').count(),0);
assert.equal(await page.locator('#compose').evaluate(e=>getComputedStyle(e).position),'sticky');
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('#message').click();
assert.equal(await page.locator('#message').evaluate(e=>document.activeElement===e),true);
await page.locator('#message').fill('保留草稿');
await page.locator('#choose-task').click();
await page.locator('#project-filter').selectOption('');
await page.locator('#task-search').fill('task-one');
await page.locator('.task-card').click();
await page.waitForFunction(()=>!document.querySelector('#task-dialog').open);
assert.equal(await page.locator('#message').inputValue(),'');
await page.locator('#choose-task').click();
await page.locator('#task-search').fill('task-two');
await page.locator('.task-card').click();
await page.waitForFunction(()=>!document.querySelector('#task-dialog').open);
assert.equal(await page.locator('#message').inputValue(),'保留草稿');
await page.context().grantPermissions(['clipboard-read','clipboard-write']);
await page.locator('.copy-code').click();
assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).includes('const a = 1;'));
assert.equal(await page.locator('.reading-nav').count(),0);
assert.equal(await page.locator('#stop').isVisible(),false);
await page.locator('#message').fill('/');
assert.equal(await page.locator('.slash-option').count(),5);
await page.locator('#message').fill('/status');
await page.locator('#send').click();
assert.equal(executions.length,0,'slash status must not become a model message');
assert.ok((await page.locator('#command-feedback').innerText()).includes('已连接'));
await page.locator('#message').fill('/unsupported');
await page.locator('#send').click();
assert.ok((await page.locator('#error').innerText()).includes('暂不支持'));
assert.equal(executions.length,0);
await page.locator('#message').fill('保留草稿');
await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/commands')&&r.request().postDataJSON().method==='turn/start'),page.locator('#send').click()]);
assert.equal(await page.locator('#send').isDisabled(),true);
await page.locator('#send').evaluate(button=>button.click());
assert.equal(executions.length,1);
assert.deepEqual(executions[0].params,{threadId:'task-two',input:[{type:'text',text:'保留草稿'}]});
active['task-two']='turn-live';
receipts.set(executions[0].key,{status:'completed',result:{turn:{id:'turn-live'}}});
await page.waitForFunction(()=>document.querySelector('#send').getAttribute('aria-label')==='追加到当前执行'&&!document.querySelector('#send').disabled);
assert.equal(await page.locator('#message').inputValue(),'');
await page.locator('#message').fill('追加要求');
await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/commands')&&r.request().postDataJSON().method==='turn/steer'),page.locator('#send').click()]);
assert.deepEqual(executions[1].params,{threadId:'task-two',input:[{type:'text',text:'追加要求'}],expectedTurnId:'turn-live'});
receipts.set(executions[1].key,{status:'completed',result:{}});
await page.waitForFunction(()=>!document.querySelector('#stop').disabled);
await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/commands')&&r.request().postDataJSON().method==='turn/interrupt'),page.locator('#stop').click()]);
assert.equal(await page.locator('#stop').isDisabled(),true,'stop must lock while its receipt is pending');
assert.equal(await page.locator('#send').isDisabled(),true);
await page.locator('#stop').evaluate(button=>button.click());
assert.equal(executions.length,3);
assert.deepEqual(executions[2].params,{threadId:'task-two',turnId:'turn-live'});
delete active['task-two'];
receipts.set(executions[2].key,{status:'completed',result:{}});
await page.waitForFunction(()=>document.querySelector('#send').getAttribute('aria-label')==='发送新一轮'&&!document.querySelector('#send').disabled);
approvals=[{id:'command',method:'item/commandExecution/requestApproval',params:{threadId:'task-two',command:'echo test',cwd:'/Code/beta',reason:'验证'}},{id:'question',method:'item/tool/requestUserInput',params:{threadId:'task-two',questions:[{id:'q',question:'选择方式',options:[{label:'快速',description:'先完成主要部分'}]}]}}];
await page.locator('#jump-approvals').waitFor({state:'visible'});
await page.locator('#approvals select').selectOption('快速');
assert.equal(await page.locator('#approvals input').inputValue(),'快速');
await page.locator('#approvals input').fill('保留正在输入的回答');
approvals=approvals.slice(1);
await page.waitForFunction(()=>document.querySelectorAll('.approval-card').length===1);
assert.equal(await page.locator('#approvals input').inputValue(),'保留正在输入的回答');
await page.getByRole('button',{name:'提交回答',exact:true}).click();
assert.equal(answers.length,1);
assert.deepEqual(answers[0],{id:'question',result:{answers:{q:{answers:['保留正在输入的回答']}}}});
assert.equal(await page.getByRole('button',{name:'提交回答',exact:true}).isDisabled(),true);
approvals=[];
await page.locator('#jump-approvals').waitFor({state:'hidden'});
events=[{method:'turn/completed',params:{threadId:'task-two'}}];
await readRequested.promise;
await page.locator('#choose-task').click();
await page.locator('#task-search').fill('task-one');
await page.locator('.task-card').click();
await page.waitForFunction(()=>!document.querySelector('#task-dialog').open);
events=[{method:'item/agentMessage/delta',params:{threadId:'task-one',delta:'NEW TASK LIVE'}}];
receipts.set(readKey,{status:'completed',result:{thread:{turns:[{items:[{type:'agentMessage',text:'OLD TASK CONTENT'}]}]}}});
await page.waitForFunction(()=>document.querySelector('#events').textContent.includes('NEW TASK LIVE'));
assert.ok(!(await page.locator('#history').innerText()).includes('OLD TASK CONTENT'),'late old task history must not overwrite current task');
await page.locator('#choose-task').click();
await page.locator('#task-search').fill('task-two');
await page.locator('.task-card').click();
await page.waitForFunction(()=>!document.querySelector('#task-dialog').open);
await page.locator('#message').fill('/new');
await page.locator('#send').click();
assert.equal(await page.locator('#project-choice').inputValue(),'/Code/beta');
assert.equal(await page.locator('#project-path').isVisible(),false);
assert.equal(await page.locator('#workspace-choice').inputValue(),'/Code/beta');
await page.locator('#project-choice').selectOption('');
assert.equal(await page.locator('#project-path').isVisible(),true);
assert.equal(await page.locator('#workspace-choice').isVisible(),false);
await page.locator('#project-choice').selectOption('/Code/alpha');
assert.equal(await page.locator('#workspace-choice option').count(),2);
await page.locator('#workspace-choice').selectOption('/Code/shared');
assert.equal(await page.locator('#workspace-path').innerText(),'/Code/shared');
await page.locator('#create').click();
await page.waitForFunction(()=>!document.querySelector('#new-dialog').open||document.querySelector('#new-error').textContent);
assert.equal(await page.locator('#new-error').innerText(),'','new task must open without resuming a nonexistent rollout');
assert.equal(created,'/Code/shared');
assert.deepEqual(creationParams,{cwd:'/Code/shared',projectId:'native-alpha',runtimeWorkspaceRoots:['/Code/shared']});
assert.equal(await page.locator('#project-choice option').count(),3,'each desktop project is one choice regardless of root count');
await page.locator('#message').fill('新任务第一条指令');
await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/commands')&&r.request().postDataJSON().method==='turn/start'),page.locator('#send').click()]);
assert.deepEqual(executions.at(-1).params,{threadId:'new',input:[{type:'text',text:'新任务第一条指令'}]});
receipts.set(executions.at(-1).key,{status:'completed',result:{turn:{id:'new-turn'}}});
await page.waitForFunction(()=>!document.querySelector('#send').disabled);
await page.locator('#choose-task').click();
await page.locator('#task-search').fill('task-two');
await page.locator('.task-card').click();
await page.waitForFunction(()=>!document.querySelector('#task-dialog').open);
await page.waitForFunction(()=>document.documentElement.scrollHeight-scrollY-innerHeight<80);
await page.evaluate(()=>window.scrollTo(0,0));
await page.waitForFunction(()=>scrollY===0);
await page.evaluate(()=>document.querySelector('#history').append(Object.assign(document.createElement('p'),{textContent:'模拟迟到的图片或内容'})));
await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
assert.equal(await page.evaluate(()=>scrollY),0,'reading older messages must not jump to bottom');
await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));
await page.waitForFunction(()=>document.documentElement.scrollHeight-scrollY-innerHeight<80);
await page.locator('#message').fill('/model test-model');
await page.locator('#send').click();
assert.equal(await page.locator('#model-label').innerText(),'test-model');
await page.locator('#message').fill('用选择的模型发送');
await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/commands')&&r.request().postDataJSON().method==='turn/start'),page.locator('#send').click()]);
assert.equal(executions.at(-1).params.model,'test-model');
assert.equal(executions.at(-1).params.threadId,'task-two');
receipts.set(executions.at(-1).key,{status:'completed',result:{turn:{id:'selected-model-turn'}}});
await page.waitForFunction(()=>!document.querySelector('#send').disabled);
for (const width of [320,390,768,1280]) {
 await page.setViewportSize({width,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`page overflow at ${width}px`);
 await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));
 const menu = await page.locator('#choose-task').boundingBox();
 assert.ok(menu.y>=0&&menu.y<80,`sidebar control must remain at top while reading at ${width}px`);
 await page.locator('#choose-task').click();
 await page.waitForFunction(()=>Math.abs(document.querySelector('#task-dialog').getBoundingClientRect().left)<1);
 assert.equal(await page.locator('#choose-task').getAttribute('aria-expanded'),'true');
 await page.keyboard.press('Escape');
 await page.waitForFunction(()=>document.querySelector('#choose-task').getAttribute('aria-expanded')==='false');
 assert.equal(await page.locator('#choose-task').evaluate(e=>document.activeElement===e),true);
}
await page.setViewportSize({width:390,height:844});
await page.locator('#choose-task').click();
await page.mouse.click(388,420);
await page.waitForFunction(()=>!document.querySelector('#task-dialog').open);
assert.deepEqual(errors,[]);
console.log('PASS: start/steer/interrupt parameters and pending controls; task search and project choice; message rendering; drafts; approvals; delayed history isolation; 320–1280px widths. Mock API only.');
} finally {await browser.close();}
